### ISSUE TITLE
Multiplication error in convolution product

### ISSUE THREAD

**Issue by aurelienpierre** [pyFFTW/pyFFTW#195]
Hi !
I'm trying to code a fast convolution product function in Cython. I have this code with Numpy, which works well except it's awefully slow :

```
cdef np.ndarray[DTYPE_t, ndim=2] convolve(np.ndarray[DTYPE_t, ndim=2] a, np.ndarray[DTYPE_t, ndim=2] b, str domain):
    cdef int MK =  b.shape[0]
    cdef int NK = b.shape[1]
    cdef int M = a.shape[0]
    cdef int N = a.shape[1]

    #cdef np.ndarray[np.complex64_t, ndim=2] ahat, bhat, chat
    #cdef np.ndarray[DTYPE_t, ndim=2] c

    ahat = np.fft.rfft2(a, (M + MK -1, N + NK -1))#.output_array
    bhat = np.fft.rfft2(b, (M + MK -1, N + NK -1))#.output_array

    cdef int Y, X

    if domain =="same":
        Y = M
        X = N
    elif domain == "valid":
        Y = M - MK + 1
        X = N - NK + 1
    elif domain == "full":
        Y = M + MK - 1
        X = N + NK - 1
    else:
        raise SyntaxError

    chat = ahat * bhat
    c = np.fft.irfft2(chat, (Y, X)).astype(np.float32)#.output_array

    return c
```

Now if I use the pyFFTW version:

```
cdef np.ndarray[DTYPE_t, ndim=2] convolve(np.ndarray[DTYPE_t, ndim=2] a, np.ndarray[DTYPE_t, ndim=2] b, str domain):
    cdef int MK =  b.shape[0]
    cdef int NK = b.shape[1]
    cdef int M = a.shape[0]
    cdef int N = a.shape[1]

    #cdef np.ndarray[np.complex64_t, ndim=2] ahat, bhat, chat
    #cdef np.ndarray[DTYPE_t, ndim=2] c

    ahat = pyfftw.builders.rfft2(a, (M + MK -1, N + NK -1)).output_array
    bhat = pyfftw.builders.rfft2(b, (M + MK -1, N + NK -1)).output_array

    cdef int Y, X

    if domain =="same":
        Y = M
        X = N
    elif domain == "valid":
        Y = M - MK + 1
        X = N - NK + 1
    elif domain == "full":
        Y = M + MK - 1
        X = N + NK - 1
    else:
        raise SyntaxError

    chat = ahat * bhat
    c = pyfftw.builders.irfft2(chat, (Y, X)).astype(np.float32).output_array

    return c
```

I get 
```
RuntimeWarning: invalid value encountered in multiply  result = method(*args, **kw)
sys:1: RuntimeWarning: overflow encountered in multiply
sys:1: RuntimeWarning: invalid value encountered in multiply
```
and an output full of `NaN`.

Do you have any clue about what could possibly go wrong in the multiplication that doesn't affect numpy ?

**Comment by hgomersall** [comment]
You're not really using pyfftw properly. The builders return an FFTW object, they don't actually do the FFT - you have to call the returned FFTW object for that. Moreover, you don't want to be doing the building _inside_ your function - best is to use a class that maintains knowledge of the FFTW object. You can always use `pyfftw.interfaces` if you want a quick speed-up, but be aware you'll potentially take a speed hit.

[Here](https://stackoverflow.com/a/15165621/709852) is a StackOverflow answer I wrote that might help with your problem. SO is a better place to ask this sort of question than github (which is intended for issues with pyfftw itself). I don't think you need to use cython to get the speed up you want - it significantly adds to the complexity if your software so unless you're using it already it's best to avoid it.

I also suggest reading the tutorial carefully to understand how pyfftw works.

Closing because this isn't an issue with pyfftw AFAICT and SO is a better forum for the question. I suggest re-asking there (I'll be notified if you tag it with pyfftw).

**Comment by aurelienpierre** [comment]
Ok thanks for your answer, sorry for the noise here.

But… man I just understood how pyFFTW works and using a Numpy-like interface for the builder functions is a nasty trick ! It's very confusing since what happens inside a `pyfftw.builder` has nothing to do with a Numpy ufunc.

I think your doc should mention from the beginning that the neither the FFTW object nor the builders  trigger an actual FFT, and the FFTW object is more than just a Python storage class, but reserves a low-level memory space where FFT**s** happen and plans the best method to do the conversion **later**. So it just prepares the space and schemes. 

The most confusing part is the need to send twice the same arrays to the builders, once calling the builder method and storing the output in a variable, then calling the variable again with the same arrays. It should be made clear that the first call uses only the shape and types of the arrays to initialize the memory space, and the second actually perform the FFT.

Well, are you open to contributions to your doc ?

**Comment by hgomersall** [comment]
I'm happy to have doc PRs. I'm not sure what needs adding though - the [tutorial](http://pyfftw.readthedocs.io/en/latest/source/tutorial.html) covers this quite carefully, and the [API documentation](http://pyfftw.readthedocs.io/en/latest/source/pyfftw/builders/builders.html) is quite explicit.

That said, if you think you can add to it then by all means do so. I'd be grateful for your input.

**Comment by aurelienpierre** [comment]
>  and the API documentation is quite explicit.

For a guy who already knows the C FTTW, maybe, but coming from numpy, it's confusing. And that could explain most of the questions you got on SO with people basically not understanding what they were doing.

**Comment by hgomersall** [comment]
Great, I look forward a PR ;) Thanks!
