### ISSUE TITLE
Wisdom not importing properly. The solution proposed in Issue #110 doesn't work.

### ISSUE THREAD

**Issue by s-sajid-ali** [pyFFTW/pyFFTW#223]
This is the same issue as [110](https://github.com/pyFFTW/pyFFTW/issues/110). Pickling and saving the wisdom doesn't work.

[Here](https://pastebin.com/phX74Ac1) is the code.

What the code does :  

Perform a 2D FFT, save wisdom, forget wisdom, import wisdom, perform the same FFT with 'Wisdom_Only' flag.

Output : 
```
(intelpy3) [sajid@xrmlite tests]$ python test_wisdom_import.py
10000 4 3.1428067684173584
Traceback (most recent call last):
  File "test_wisdom_import.py", line 64, in <module>
    FFT2(a,flag='WISDOM_ONLY',threads=t)
  File "test_wisdom_import.py", line 18, in FFT2
    threads=threads, planning_timelimit=None)
  File "pyfftw/pyfftw.pyx", line 1110, in pyfftw.pyfftw.FFTW.__cinit__ (/tmp/sajid/spack-stage/spack-stage-059qa7rl/pyFFTW-0.10.4/pyfftw/pyfftw.c:10829)
RuntimeError: No FFTW wisdom is known for this plan.
```

**Comment by grlee77** [comment]
I believe the problem lies in the flags you are passing to FFTW in your example.  On the first run you pass the flag 'FFTW_ESTIMATE', but then you **did not also use this flag** when passing 'FFTW_WISDOM_ONLY'.  This results in defaulting to `FFTW_MEASURE' for the effort which is a higher effort level than the previously created plan stored in your wisdom.

You would need to be passing the final FFTW call within your FFT2 function `flags=('FFTW_ESTIMATE', 'FFTW_WISDOM_ONLY')` and then it should work.  Alternatively, using 'FFTW_MEASURE' when generating the wisdom should also work.

IIRC, the rule for planner efforts is that the wisdom must contain a plan at an equal or higher level of effort for it to be used.

**Comment by hgomersall** [comment]
I concur with @grlee77 .

As an aside, the pattern you use for doing the FFT is not so good. It might just be an example, but as written you're going to be creating the FFT object every time. I suspect if simplicity is what you're after, you'd do better to use the `interfaces` methods (which can at least do some caching of the FFTW objects), otherwise use a class.

**Comment by s-sajid-ali** [comment]
@grlee77  : Thank you ! 

@hgomersall  : Thanks for the advice. Does this mean I create and initialize a pyfftw builder class instead of a python function that I've used above ? 
[This](https://github.com/s-sajid-ali/multislice/blob/master/multislice/fft_utils.py) is my usage of pyfftw at the moment, though I've reverted to intel's mkl-fft monkey patched to numpy.fft at the moment but I want to spread my calculations over multiple nodes in the future. 

Another question is that I've seen that pyfftw gives better absolute performance if the number of cores are set correctly and if wisdom is used. I've found no documentation which suggests how one should set the number of threads for a given fft size. Is there a way to know beforehand ? 

I would like to contribute to the MPI based wrapper for pyfftw since I also need it for my work. I did see that you guys were planning on making that functionality available in the next release and I'd like to get involved.

**Comment by hgomersall** [comment]
@s-sajid-ali yeah, you should have a builder class. Alternatively, the [`interfaces`](http://pyfftw.readthedocs.io/en/latest/source/pyfftw/interfaces/interfaces.html) has a cache feature which removes much of the overhead of creating the FFTW object, and allows simple monkey patching. It should certainly be better than the way you've done it.

I have little to do with the MPI stuff. I suggest getting in touch with @fredRos on that issue - I've no doubt he'd appreciate contributions.

**Comment by hgomersall** [comment]
@s-sajid-ali [Here's](https://stackoverflow.com/a/30615425/709852) an example of using pyFFTW with a builder class. It's more than you need, but it shows the principles.

**Comment by s-sajid-ali** [comment]
@hgomersall  : Thank you! I'll go through it and change my implementation! I'll join the thread where the discussion for the next release is going on then.

Any response to the issue of utilizing optimal number of threads ?

**Comment by s-sajid-ali** [comment]
The threads issue is discussed here : http://www.fftw.org/fftw3_doc/How-Many-Threads-to-Use_003f.html#How-Many-Threads-to-Use_003f
