### ISSUE TITLE
[Documentation] Add warning about default FFTW axes value

### ISSUE THREAD

**Issue by mattpalermo** [pyFFTW/pyFFTW#225]
It took me far too long to figure out that the default value of the axes argument to the FFTW class constructor doesn't have the same behaviour as numpy.fft or scipy.fftpack. In those other libraries the default is to transform all axes. It seems that the default behaviour of FFTW is to only transform the last axis.

Maybe a warning in the constructor argument documentation would help the next silly bugger :)

**Comment by hgomersall** [comment]
For the `FFTW` class? That doesn't have an API anything like numpy or scipy so it seems strange it should inherit any kind of behaviour from them. The [`interfaces`](http://pyfftw.readthedocs.io/en/latest/source/pyfftw/interfaces/interfaces.html) are designed to look like numpy or scipy, so if the issue is there, please can you clarify which one you mean.

**Comment by mattpalermo** [comment]
I am referring to the `FFTW` class. It was clear that the API is not meant to resemble numpy or scipy but maybe the statement "This argument is equivalent to the same argument in numpy.fft.fftn()" lead me to my false assumptions.

**Comment by chrisvalx** [comment]
the `axes=(-1)` default value and the multiple axes behavior of the `FFTW` class are documented in the class API docs, as is the difference to NumPy's behavior. I think this issue can be closed.

**Comment by hgomersall** [comment]
Yeah, I agree. Thanks!
