### ISSUE TITLE
Which libfftw does it link to in the conda-forge version?

### ISSUE THREAD

**Issue by Varato** [pyFFTW/pyFFTW#244]
Firstly, thanks for writing this nice package,
but I am recently confused while installing pyfftw by conda.

My mac never has fftw3 installed anywhere. But within a conda env, I can still do a `conda install -c conda-forge pyfftw`. After that, I want to check which libfftw it links to. But a `otool -L pyfftw.cpython-36-darwin.so` gives me:

```
$ otool -L pyfftw.cpython-36-darwin.so
pyfftw.cpython-36m-darwin.so:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```
Meaning no libfftw was linked during installation. But pyfftw still works!
```
>>> import pyfftw
>>> a = pyfftw.empty_aligned(4, "float64")
>>> b = pyfftw.empty_aligned(3, "complex128")
>>> a[:] = [1,2,3,4]
>>> fft = pyfftw.FFTW(a,b)
>>> fft()
array([10.+0.j, -2.+2.j, -2.+0.j])
```
I really want to know how and why.

**Comment by grlee77** [comment]
The conda-forge build of pyFFTW is **statically** linked to FFTW and I think you will only see dynamically linked libraries with `otool -L`. 

The static linking is requested by setting an environment variable as seen here:
https://github.com/conda-forge/pyfftw-feedstock/blob/f7a03a7507a1bc6930029631ffb2007389811745/recipe/build.sh#L6

and was done to avoid issues with Numpy+mklfft being installed along side pyFFTW as raised in #106

In general if you are using FFTW from conda-forge, the FFTW libraries live within the `lib` subfolder of your conda environment (e.g. something like /home/<username>/anaconda/<envname>/lib/libfftw*). You just don't see them listed with your command above due to the static linking.

**Comment by Varato** [comment]
Got it. Thanks for the quick response.

**Comment by jakirkham** [comment]
IIRC we could dynamically link on macOS, but not on Linux (due to the aforementioned MKL issue). If you have a need for dynamic linking on macOS, happy to discuss.

**Comment by jakirkham** [comment]
Any more questions/thoughts about this, @Varato, or is this ok to close?

**Comment by Varato** [comment]
Yes. Thanks a lot!
