### ISSUE TITLE
How to use pyfftw in python3.6 under Win10?

### ISSUE THREAD

**Issue by ChengChuanTao** [pyFFTW/pyFFTW#245]
I'm a beginner in Python, and want to install this in Python3.6 under  Win10(Other packages must install in Python3.6). However, The packages can find in Pypi is for Python3.5, and in conda there have packages in Python3.6 and Python3.7,  but only  for OSX and for linux. 

So I want to know how to use pyfftw in python3.6? Maybe compile the source code helps, but I don't know how to do it. Is there anyone that can help me? Any help will be appreciated

**Comment by paugier** [comment]
It seems to me that a pyfftw maintainer could just build and push a wheel for Python 3.6 and Windows on PyPI.  Since it works fine for Python 3.5 (see https://pypi.org/project/pyFFTW/0.10.4/#files), it could be straightforward :slightly_smiling_face: 

Then, @ChengChuanTao you would be able to install pyfftw just with `pip install pyfftw`.

**Comment by grlee77** [comment]
I am going to start making a new release now. We should have new wheels for 2.7, 3.5, 3.6 and 3.7 available on PyPI within the coming day(s).

**Comment by paugier** [comment]
Great! Thank you for your work on pyfftw!

**Comment by grlee77** [comment]
wheels for 0.11.1 are on PyPI now. please let me know if you encounter any further issues
