### ISSUE TITLE
Streaming data mode

### ISSUE THREAD

**Issue by tatulea** [pyFFTW/pyFFTW#288]
Hi,

I have a large amount of data that comes from MongoDB and I need to do real FFT on it. For now, I am getting this data and convert it into a list and then send it to rfft builder. The problem is that this list takes 12GB of RAM and is not very efficient. Is there any way to use pyFFTW and instead of giving the list as parameter to give an iterator?

**Comment by hgomersall** [comment]
Are you trying to do a FFT on all the data? One can't do a streamed FFT, but if you want to operate on sub-blocks, or have somewhere to put it without extra copies that's certainly possible. I'd need to know a bit more about the input data structures and the FFT shapes to be able to advise further...

**Comment by tatulea** [comment]
The data from my mongo aggregation looks like this:
```js
{ x: 0.1, y: 1.2, z: 0.9 }
```

There are three axis (x, y, z) and I am making them numpy array as follow:

```python
data_frame = pd.DataFrame(list(agg))

accel_x = np.array(data_frame.get('x', []), dtype='float64')
accel_y = np.array(data_frame.get('y', []), dtype='float64')
accel_z = np.array(data_frame.get('z', []), dtype='float64')
```

Then I am doing rfft on each aceel_*.

**Comment by hgomersall** [comment]
Ooof! How about the following:
```
x_array = pyfftw.zeros_aligned((x_size), dtype='float64')
rfft_x = pyfftw.builders.rfft(x_array)

# accel_x is likely the same as the original x_array
accel_x = rfft_x.output_array

# Now populate accel_x with each data dict. You have several options here - I guess loop
# with an index is simplest

fft_accel_x = rfft_x()
```
Does that do what you need?

**Comment by tatulea** [comment]
But populating accel_x won't get my RAM full as well? As it means I will read again the data from Mongo and store it in RAM.

Another option may be to read data from Mongo in batches, but I am not sure how to compute multiple FFT batches to get the final one. This option would be better because I have some cases when I want to get the FFT on some smaller intervals. For example, Mongo can have data for 8h. Once per night, I can take this data and do batches of 15mins with FFT and store them back in Mongo. During the day, if I need the FFT for the whole 8h it can "merge" those 15mins batches and return me the final one. If I want it for 45mins, I can just "merge" the batches for this period.

My problem with this approach is how to merge those batches.

**Comment by HaHeho** [comment]
> My problem with this approach is how to merge those batches.

That very much depends on the content of your input data and the goal of your analysis.
What kind of data is this (displacement data)?
Is it hours of data at a very high sampling frequency?
Is it possible to maybe downsample the data (since the oscillations you are interested in are only at low frequency components anyways)? 
Does batch processing and subsequent averaging of magnitude spectra yield a meaningful result?
Is the data expected show strong variations or be rather monotonous over a day (analyzing the entire signal might not be meaningful anyways then)?

Answering these questions can tell you whether batch averaging or splitting into batches (and investigating changes over time) are suitable to yield the information that your are eventually interested in.

**Comment by tatulea** [comment]
It is accelerometer data at a sampling of 3.3kHz. I cannot lower down the frequency. The data differs during the day, but there may be some intervals where it doesn't change too much.

**Comment by hgomersall** [comment]
You're really not giving us much to go on! What you should do is dependent on what your data looks like and what you're trying to achieve with an FFT. What _are_ you trying to achieve with an FFT?

**Comment by tatulea** [comment]
The input data for the FFT is from an accelerometer which monitors vibration. The FFT should give me the frequencies of the vibration, ideally for specific periods of time.

**Comment by HaHeho** [comment]
Since you are mentioning "specific periods in time", you will have to decide on how to partition your data in time!

I suppose what you are looking for is something like a Spectrogram (https://en.wikipedia.org/wiki/Spectrogram), not a single spectrum over the entirety of data. Matplotlib (https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.specgram.html) already does that for you, although I expect it also will not be able to deal with that amount of data. 

In that case, you will probably need to build the analysis and plotting behavior yourself. My recommendation would be to query appropriate blocks from the database, perform the FFT, and subsample / interpolate the resulting spectrum before storing them (probably `Numpy.save()` or something). This can be performed on a regular basis. A different script could then load the lower-resolution spectra and visualize the data like a Spectrogram (https://matplotlib.org/3.1.0/gallery/mplot3d/surface3d.html in a 2D view should be suitable).

How to query your data from MongoDB without overwhelming your entire system memory is something you will have to look for in other places.

**Comment by hgomersall** [comment]
I'm going to close this issue as not relevant to pyFFTW, but feel free to continue the discussion.
