### ISSUE TITLE
update interfaces to support new normalization options

### ISSUE THREAD

**Issue by grlee77** [pyFFTW/pyFFTW#295]
This PR is a reminder that we will likely need to update the numpy and scipy interfaces to support additional `norm` options after a future NumPy release.

Currently the only options are:
1.) 1/N normalization on the inverse transform  (when `norm=None`)
2.) 1/sqrt(N) on both (when `norm='ortho'`)

https://github.com/numpy/numpy/pull/16476 adds two additional keyword options.:
1.) norm='backward' is an alias for the current `norm=None` behavior and applies 1/N normalization during inverse transforms only
2.) norm='forward' applies 1/N normalization during the forward transforms only
see also: https://github.com/numpy/numpy/issues/16126

**Comment by chrisvalx** [comment]
Hello, I'm interested in working on implementing this interface change. I worked on extending the `numpy.fft` normalization options referenced in [numpy/numpy#16476](https://github.com/numpy/numpy/pull/16476), so I thought I could help bring the change to `pyFFTW` as well. 

I'd like to ask you if you think the `numpy.fft` `norm` changes should carry over to the `numpy` interface only, or to the builders API as well. I understand that the builders are supposed to make the `FFTW` class easier to work with, while resembling the behavior of `numpy.fft`. At the moment the builders accept the `norm` parameter values `None` and `ortho` like `numpy` used to do; should I extend those as well so that they can accept the `norm` values `None`/`backward`, `forward` and `ortho` like `numpy` currently does?  

I think that would be the best thing to do, so that the builders still present the full functionality of `numpy.fft` while returning an `FFTW` instance, but I wanted to check with you first.

**Comment by hgomersall** [comment]
Great!

I think including it in the builders would be preferable. It was always the intent that the builders interface tracks the numpy interface as closely as possible.

**Comment by JeppeKlitgaard** [comment]
I think #330 closes this? 🎉
