### ISSUE TITLE
pyfftw is slower than default backend

### ISSUE THREAD

**Issue by Freakwill** [pyFFTW/pyFFTW#310]
Following is the result of the test.

Time with scipy.fft default backend: 0.166 seconds
Time with pyfftw backend installed: 0.336 seconds

ps: python3.8 macOS10.15

**Comment by hgomersall** [comment]
How did you test it?

**Comment by Freakwill** [comment]
> How did you test it?

run the example in a script. It shown that pyfftw is faster for array with shape (1280, 64)

**Comment by hgomersall** [comment]
> run the example in a script. It shown that pyfftw is faster for array with shape (1280, 64)

I meant show me the code.

**Comment by HaHeho** [comment]
As soon as you include some higher planning effort like `pyfftw.config.PLANNER_EFFORT = 'FFTW_MEASURE'` in that example, you should get better performance. See http://www.fftw.org/fftw3_doc/Planner-Flags.html.

**Comment by KDMortimer** [comment]
I have observed the same effect in my own testing of pyfftw, but I've had a small problem in implementing the "solution": 
Although the scipy backend completes the the calculation I'm performing in under 2 seconds, once I switch to the pyfftw backend with `pyfftw.config.PLANNER_EFFORT = 'FFTW_MEASURE'`, the calculation seems to take much, much, much longer. Either the calculation is hanging for me or it's at least a factor of 100x slower. I can provide further details if that would help identify the problem.

Really all I am doing is a `scipy.fft.rfft` on a 38.4 million point 24-bit dataset. In the absence of `PLANNER_EFFORT`, the pyfftw backend was roughly 3x slower (taking about 5 seconds to complete). 

I don't believe the issue is with my computer or hardware, as using the demo code in your documentation (reproduced above by Freakwill), I was measuring the computation time as less than 0.01 seconds and the pyfftw backend as taking 60% longer (I believe the exact numbers were 0.003s and 0.005s, but I did not write them down at the time).
